#!/usr/local/sbin/charm-env python3

import os

from subprocess import call

from charms.layer import options

from charms.layer.git_deploy import update_to_commit

from charmhelpers.core.host import chdir
from charmhelpers.core.hookenv import (
    action_get,
    status_set,
)

if __name__ == "__main__":
    opts = options('git-deploy')
    commit_or_branch = action_get("commit-or-branch")
    current = os.path.join(opts.get('target'), 'current')
    status_set('maintenance', "Updating presentation")
    update_to_commit('master', current)

    with chdir(os.path.join(opts.get('target'), 'current')):
        sphinx_build_cmd = 'sphinx-build -b html source %s' % opts.get('target')
        call(sphinx_build_cmd.split(), shell=False)
    status_set('active', "Presentation ready")
