#!/bin/bash

commit = action-get commit

if [[ commit == "" ]]; then
  echo "Cannot update to a commit without a commit"
  exit 0
fi

cd $(config-get app-path)
git fetch origin master
git checkout $(action-get commit)
sphinx-build -b html source $(config-get app-path)
chown -R www-data:www-data $(config-get app-path)

